external:
  endpoints:
    github:
      USER: https://api.github.com/users/{username}
      REPOS: https://api.github.com/users/{username}/repos

#logging:
#  level:
#    root: DEBUG

# TODO: Understand why this no longer works and find proper replacement
#spring:
#  jackson:
#    property-naming-strategy: SNAKE_CASE
